receivers:
  kafka:
    brokers:
      - $EVENTHUB_ENDPOINT
    protocol_version: 1.0.0
    topic: "$EVENTHUB_NAME"
    encoding: "otlp_proto"
    client_id: "$CLIENT_ID"
    group_id: "$CONSUMER_GROUP"
    metadata:
      full: false
    auth:
      sasl:
        mechanism: "PLAIN"
        username: "$$ConnectionString"
        password: "$EVENTHUB_LISTEN_CONNECTION_STRING"
        version: 1
      tls:
        insecure: true
    initial_offset: latest

processors:
  batch:
  attributes:
    actions:
      - key: "processor.name"
        action: insert
        value: "$PROCESSOR_NAME"

exporters:
  otlp/refinery:
    endpoint: $REFINERY_ENDPOINT:4317
    headers:
      "x-honeycomb-team": "$HONEYCOMB_API_KEY"
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces/default:
      receivers: [kafka]
      processors: [attributes, batch]
      exporters: [otlp/refinery]
